# Generated by Django 4.2.7 on 2023-11-05 20:34

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("text", wagtail.blocks.RichTextBlock()),
                            ("html", wagtail.blocks.RawHTMLBlock()),
                        ],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
                (
                    "seo_img",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image for social media, size 1200×628 pixels",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="Home",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("subtitle", models.CharField(blank=True, default="", max_length=150)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("html", wagtail.blocks.RawHTMLBlock())],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
                (
                    "seo_img",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image for social media, size 1200×628 pixels",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog",
                "verbose_name_plural": "Blog",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("menu_subtitle", models.CharField(default="", max_length=200)),
                ("subtitle", models.CharField(blank=True, default="", max_length=150)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("html", wagtail.blocks.RawHTMLBlock())],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
                (
                    "menu_icon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "seo_img",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image for social media, size 1200×628 pixels",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Category",
                "verbose_name_plural": "Blog Categories",
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
